name: Deploy to Apprisma ServerCA

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to SiteGround via SSH
        uses: appleboy/scp-action@master
        with:
          host: ssh.apprisma.com
          username: u173-cmrrergzqblu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 18765
          source: "."
          target: "/home/customer/www/apprisma.com/public_html"